# Generated by Django 5.0.2 on 2024-03-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('publication_sign', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('number_of_views', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'название блога',
                'verbose_name_plural': 'названия блогов',
            },
        ),
    ]
