# Generated by Django 5.0.2 on 2024-02-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-name',), 'verbose_name': 'название продукта', 'verbose_name_plural': 'названия продуктов'},
        ),
    ]
