# Generated by Django 5.0.2 on 2024-03-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='version_number',
            field=models.IntegerField(verbose_name='версия №'),
        ),
    ]
